version: "3"

services:
  database:
    image: "game_database"
    build: ./database
    restart: always
    volumes:
      - ./database/data:/data/db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
    networks:
      - backend

  api:
    image: "game_api"
    build:
      context: ./api
    container_name: api
    depends_on:
      - database
    networks:
      - web
      - backend
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_NAME=test
      - DB_LOGGING=true
      - DB_SYNC=true

  web:
    image: "game_web"
    build: ./web
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - web
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:8080

networks:
  web:
    driver: bridge
  backend:
    driver: bridge
