name: Web pipeline

on: [push, pull_request]

env:
  CI: true
  REACT_APP_API_ENDPOINT: http://localhost:8000

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [13, 14]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: cd web && npm ci

      - name: Run lint
        run: cd web && npm run lint

      - name: Run build
        run: cd web && npm run build

      - name: Run tests
        run: cd web && npm run test -- --maxWorkers=2
